apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app: java-kafka-producer
  name: java-kafka-producer
spec:
  containers:
    - name: java-kafka-producer
      image: docker.io/mezzeddine/producer24-1-2022:v1
      restartPolicy: Never
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: TOPIC
          value: my-topic
        - name: DELAY_MS
          value: "1000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MESSAGE_COUNT
          value: "1000000"
        - name: PRODUCER_ACKS
          value: "all"
        - name: ADDITIONAL_CONFIG
          value: |
                retries=100

